import { signOffDailyCloseAction } from "@/lib/reports/daily-close-actions";
import type { DailyCloseData } from "@/lib/reports/daily-close-data";
import { formatCurrency, formatDateTime, formatServiceDate } from "@/lib/ops/utils";

function Stat({ label, value, hint }: { label: string; value: string | number; hint: string }) { return <article className="rounded-[22px] border border-[#E4E7EB] bg-[#F8FAFB] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#6B7280]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs leading-5 text-[#6B7280]">{hint}</p></article>; }
function tenderLabel(type: string) { return type === "mobile_money" ? "Mobile money" : type[0].toUpperCase() + type.slice(1); }

export function DailyCloseReport({ data, canSignOff, message }: { data: DailyCloseData; canSignOff: boolean; message?: string }) {
  const issueNotes = data.checklist ? Object.entries(data.checklist.responses).filter(([, response]) => response.status === "issue" && response.note) : [];
  return <section className="surface-card rounded-[32px] p-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] uppercase tracking-[0.18em] text-[#9CA3AF]">Daily Close</p><h2 className="mt-2 text-2xl font-semibold">{formatServiceDate(data.serviceDate)}</h2><p className="mt-2 text-sm text-[#6B7280]">Physical cash uses canonical POS cash sales, cash Money Out, and internal transfers.</p></div><form method="get" className="flex items-end gap-2"><label className="grid gap-1 text-xs font-semibold text-[#4B5563]">Service date<input name="date" type="date" defaultValue={data.serviceDate} className="rounded-xl border border-[#D9E0E6] bg-white px-3 py-2 text-sm font-normal" /></label><button className="rounded-full border border-[#D9E0E6] bg-white px-4 py-2 text-sm font-semibold">Load</button></form></div>
    {message ? <p className="mt-4 rounded-[18px] border border-[#D8E1F4] bg-[#F5F8FF] px-4 py-3 text-sm text-[#46699B]">{message}</p> : null}
    {data.snapshot ? <div className="mt-4 rounded-[20px] border border-[#CCE4D2] bg-[#F3FBF5] px-4 py-3 text-sm"><p className="font-semibold text-[#287241]">Locked by {data.snapshot.closedByEmail} at {formatDateTime(data.snapshot.closedAt)}</p><p className="mt-1 text-[#4B5563]">Expected cash: {formatCurrency(data.snapshot.expectedCash)} · Actual counted: {formatCurrency(data.snapshot.cashCounted)} · Variance: {formatCurrency(data.snapshot.cashDifference)}</p></div> : null}
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Combined paid sales" value={formatCurrency(data.totalSales)} hint="POS + online paid orders, excluding cancelled orders" /><Stat label="Walk-in POS" value={formatCurrency(data.posSales)} hint="Paid walk-in sales" /><Stat label="Online sales" value={formatCurrency(data.onlineSales)} hint="Paid storefront orders" /><Stat label="Completed paid sales" value={formatCurrency(data.completedPaidSales)} hint={`${data.completedOrders} completed orders`} /></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Cash sales" value={formatCurrency(data.cashReconciliation.cashSales)} hint="Canonical paid POS cash tender amount" /><Stat label="Cash Money Out" value={formatCurrency(data.cashReconciliation.cashMoneyOut)} hint="Cash purchases and transfer fees" /><Stat label="Cash transferred out" value={formatCurrency(data.cashReconciliation.cashTransfersOut)} hint="Internal transfers leaving Cash" /><Stat label="Cash transferred in" value={formatCurrency(data.cashReconciliation.cashTransfersIn)} hint="Internal transfers entering Cash" /></div>
    <p className="mt-3 rounded-[18px] bg-[#F8FAFB] px-4 py-3 text-sm font-semibold">Before opening cash: {formatCurrency(data.cashReconciliation.expectedCashBeforeOpening)}. Final expected cash = opening cash + this amount.</p>
    {data.cashReconciliation.cashActivityExists && !data.cashReconciliation.mobileMoneyDepositRecorded ? <p className="mt-3 rounded-[18px] border border-[#F0D9B8] bg-[#FFF9EE] px-4 py-3 text-sm font-semibold text-[#8A5B12]">No Mobile Money deposit recorded for this service day.</p> : null}
    <div className="mt-5 grid gap-4 xl:grid-cols-2"><section className="rounded-[24px] border border-[#E4E7EB] bg-white p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9CA3AF]">POS tender reconciliation</p><h3 className="mt-2 text-lg font-semibold">Walk-in sales only</h3><div className="mt-4 overflow-hidden rounded-[16px] border border-[#E4E7EB]"><table className="w-full text-sm"><thead className="bg-[#F8FAFB] text-left text-xs text-[#6B7280]"><tr><th className="px-3 py-2">Tender</th><th className="px-3 py-2 text-right">Sales</th><th className="px-3 py-2 text-right">Received</th><th className="px-3 py-2 text-right">Change</th></tr></thead><tbody>{data.posTenders.map((tender) => <tr key={tender.type} className="border-t border-[#EEF2F6]"><td className="px-3 py-2 font-medium">{tenderLabel(tender.type)} ({tender.count})</td><td className="px-3 py-2 text-right">{formatCurrency(tender.amount)}</td><td className="px-3 py-2 text-right">{formatCurrency(tender.received)}</td><td className="px-3 py-2 text-right">{formatCurrency(tender.change)}</td></tr>)}</tbody></table></div><p className="mt-3 text-sm font-semibold">Expected POS cash: {formatCurrency(data.expectedPosCash)}</p></section>
      <section className="rounded-[24px] border border-[#E4E7EB] bg-white p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9CA3AF]">Closing controls</p><h3 className="mt-2 text-lg font-semibold">Checklist and exceptions</h3><p className="mt-3 text-sm">End-of-day checklist: <span className="font-semibold">{data.checklist ? `completed by ${data.checklist.submittedByEmail}` : "not completed"}</span></p><p className="mt-2 text-sm">Open paid orders: <span className="font-semibold">{data.openPaidOrders.length}</span> · Pending payment orders: <span className="font-semibold">{data.pendingPaymentOrders}</span> · Cancelled: <span className="font-semibold">{data.cancelledOrders}</span></p>{issueNotes.length ? <div className="mt-3 space-y-2">{issueNotes.map(([id, response]) => <p key={id} className="rounded-xl bg-[#FFF8E8] px-3 py-2 text-xs text-[#8A5B12]">{id.replaceAll("_", " ")}: {response.note}</p>)}</div> : null}</section></div>
    {data.openPaidOrders.length ? <section className="mt-5 rounded-[24px] border border-[#E4E7EB] bg-white p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9CA3AF]">Open paid orders</p><div className="mt-3 grid gap-2">{data.openPaidOrders.map((order) => <p key={order.id} className="rounded-xl bg-[#F8FAFB] px-3 py-2 text-sm"><span className="font-semibold">{order.orderNumber}</span> · {order.orderSource === "pos" ? "POS" : "Online"} · {order.status.replaceAll("_", " ")} · {formatCurrency(order.totalAmount)}</p>)}</div></section> : null}
    {!data.snapshot && canSignOff ? <form action={signOffDailyCloseAction} className="mt-5 rounded-[24px] border border-[#D8E1F4] bg-[#F5F8FF] p-4"><input type="hidden" name="serviceDate" value={data.serviceDate} /><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#46699B]">Manager sign-off</p><p className="mt-2 text-sm text-[#4B5563]">The database derives expected cash from canonical sources. Signing off stores the actual count and locks the snapshot.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-sm font-semibold">Opening cash<input name="openingFloat" inputMode="numeric" defaultValue="0" required className="rounded-xl border border-[#D9E0E6] bg-white px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Actual Cash Counted<input name="cashCounted" inputMode="numeric" required className="rounded-xl border border-[#D9E0E6] bg-white px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Notes<input name="notes" maxLength={2000} className="rounded-xl border border-[#D9E0E6] bg-white px-3 py-2 font-normal" /></label></div><button className="mt-4 rounded-full bg-[#5E2519] px-5 py-2.5 text-sm font-semibold text-white">Sign off and lock Daily Close</button></form> : null}
  </section>;
}