import Link from "next/link";
import { requireApprovedAdminRole } from "@/lib/auth/admin-role";
import { getRawMaterialsPageData } from "@/lib/raw-materials/data";
import { createRawMaterialAction, recordRawMaterialInputAction, importRawMaterialsAction } from "@/lib/raw-materials/actions";
import { formatCurrency, formatServiceDate, getUgandaServiceDate } from "@/lib/ops/utils";
import { RawMaterialsImport } from "@/components/raw-materials/import";

export default async function RawMaterialsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireApprovedAdminRole();
  const params = await searchParams;
  const data = await getRawMaterialsPageData();
  const activeMaterials = data.materials.filter((item) => item.isActive);
  const edible = activeMaterials.filter((item) => item.category === "edible");
  const nonEdible = activeMaterials.filter((item) => item.category === "non_edible");
  const manualIdempotencyKey = crypto.randomUUID();
  return <div className="space-y-4 text-[#111418]">
    <section className="surface-card rounded-[32px] px-5 py-5"><p className="text-[11px] uppercase tracking-[0.22em] text-[#6B7280]">Inventory</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Raw Materials</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6B7280]">Track edible and non-edible inputs in their configured units. Every confirmed purchase updates stock and records one cash Money Out transaction.</p></section>
    {params.error ? <p className="rounded-[22px] border border-[#F2C6C0] bg-[#FFF4F2] px-4 py-3 text-sm text-[#8B2E23]">{params.error}</p> : null}
    <section className="grid gap-4 xl:grid-cols-2"><section className="surface-card rounded-[32px] p-5"><p className="text-[11px] uppercase tracking-[0.18em] text-[#9CA3AF]">Record Raw Material Input</p><h2 className="mt-2 text-xl font-semibold">Manual purchase</h2><form action={recordRawMaterialInputAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="idempotency_key" value={manualIdempotencyKey} /><label className="grid gap-2 text-sm"><span>Material</span><select name="raw_material_id" required className="rounded-xl border border-[#D7DDE4] bg-white px-3 py-2.5">{activeMaterials.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.unitName})</option>)}</select></label><label className="grid gap-2 text-sm"><span>Supplier</span><select name="supplier_id" required className="rounded-xl border border-[#D7DDE4] bg-white px-3 py-2.5"><option value="">Select supplier</option>{data.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label className="grid gap-2 text-sm"><span>Quantity</span><input name="quantity" type="number" min="0.01" step="0.01" required className="rounded-xl border border-[#D7DDE4] px-3 py-2.5" /></label><label className="grid gap-2 text-sm"><span>Total cost (UGX)</span><input name="total_cost_ugx" type="number" min="1" step="1" required className="rounded-xl border border-[#D7DDE4] px-3 py-2.5" /></label><label className="grid gap-2 text-sm"><span>Date received</span><input name="received_date" type="date" defaultValue={getUgandaServiceDate()} required className="rounded-xl border border-[#D7DDE4] px-3 py-2.5" /></label><label className="grid gap-2 text-sm sm:col-span-2"><span>Notes</span><textarea name="notes" rows={2} className="rounded-xl border border-[#D7DDE4] px-3 py-2.5" /></label><button className="w-fit rounded-xl bg-[#5E2519] px-4 py-2.5 text-sm font-semibold text-white">Save input</button></form></section><RawMaterialsImport materials={activeMaterials} suppliers={data.suppliers} action={importRawMaterialsAction} defaultEventDate={getUgandaServiceDate()} /></section>
    <section className="surface-card rounded-[32px] p-5"><div className="flex items-end justify-between gap-3"><div><p className="text-[11px] uppercase tracking-[0.18em] text-[#9CA3AF]">Current stock</p><h2 className="mt-2 text-xl font-semibold">Configured materials</h2></div><Link href="/reports" className="text-sm font-semibold text-[#5E2519]">View reports</Link></div><div className="mt-5 grid gap-5 md:grid-cols-2"><StockGroup title="Edible Materials" items={edible} /><StockGroup title="Non-Edible Materials" items={nonEdible} /></div></section>
    <section className="surface-card rounded-[32px] p-5"><p className="text-[11px] uppercase tracking-[0.18em] text-[#9CA3AF]">Input history</p><h2 className="mt-2 text-xl font-semibold">Recent Raw Material purchases</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-[#EEF2F6] text-xs uppercase tracking-[0.12em] text-[#9CA3AF]"><tr><th className="px-3 py-3">Date</th><th className="px-3 py-3">Material</th><th className="px-3 py-3">Quantity</th><th className="px-3 py-3">Supplier</th><th className="px-3 py-3">Cost</th><th className="px-3 py-3">Source</th><th className="px-3 py-3">Entered by</th></tr></thead><tbody>{data.purchases.map((purchase) => <tr key={purchase.id} className="border-b border-[#F2F4F6]"><td className="px-3 py-3">{formatServiceDate(purchase.receivedDate)}</td><td className="px-3 py-3 font-semibold">{purchase.materialName}<span className="ml-2 text-xs font-normal text-[#6B7280]">{purchase.category}</span></td><td className="px-3 py-3">{purchase.quantity} {purchase.unitName}</td><td className="px-3 py-3">{purchase.supplierName}</td><td className="px-3 py-3">{formatCurrency(purchase.totalCostUgx)}</td><td className="px-3 py-3">{purchase.source === "excel_import" ? `Excel ${purchase.importBatchNumber ?? ""}` : "Manual"}</td><td className="px-3 py-3 text-xs">{purchase.createdBy}</td></tr>)}</tbody></table>{data.purchases.length === 0 ? <p className="rounded-xl bg-[#F8FAFB] px-4 py-4 text-sm text-[#6B7280]">No Raw Material inputs recorded yet.</p> : null}</div></section>
    <section className="surface-card rounded-[32px] p-5"><p className="text-sm font-semibold">Add a configured material</p><form action={createRawMaterialAction} className="mt-3 grid gap-3 sm:grid-cols-[1fr_180px_180px_auto]"><input name="name" required placeholder="Material name" className="rounded-xl border border-[#D7DDE4] px-3 py-2.5" /><select name="category" className="rounded-xl border border-[#D7DDE4] px-3 py-2.5"><option value="edible">Edible</option><option value="non_edible">Non-edible</option></select><input name="unit_name" required placeholder="Unit e.g. sacks" className="rounded-xl border border-[#D7DDE4] px-3 py-2.5" /><button className="rounded-xl border border-[#5E2519] px-4 py-2.5 text-sm font-semibold text-[#5E2519]">Add material</button></form></section>
  </div>;
}
function StockGroup({ title, items }: { title: string; items: Array<{ id:number; name:string; unitName:string; currentQuantity:number; reorderThreshold:number }> }) { return <div><h3 className="text-sm font-semibold text-[#4B5563]">{title}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{items.map((item) => <div key={item.id} className="rounded-[20px] border border-[#E4E7EB] bg-white p-4"><p className="font-semibold">{item.name}</p><p className="mt-2 text-2xl font-semibold">{item.currentQuantity} <span className="text-sm font-normal text-[#6B7280]">{item.unitName}</span></p>{item.reorderThreshold > 0 && item.currentQuantity <= item.reorderThreshold ? <p className="mt-1 text-xs font-semibold text-[#A14B1D]">Low stock</p> : null}</div>)}</div></div>; }
