"use client";
import { useState } from "react";
import * as XLSX from "xlsx";
import type { RawMaterial } from "@/lib/raw-materials/types";

function dateValue(value: unknown) { if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value; if (typeof value === "number") { const d = XLSX.SSF.parse_date_code(value); if (d) return `${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`; } return ""; }
export function RawMaterialsImport({ materials, suppliers, action }: { materials: Array<Pick<RawMaterial,"id"|"name">>; suppliers: Array<{id:number;name:string}>; action: (formData: FormData) => void }) {
  const [rows, setRows] = useState<any[]>([]); const [filename, setFilename] = useState(""); const [importHash, setImportHash] = useState(""); const [error, setError] = useState("");
  async function handleFile(file?: File) { if (!file) return; setError(""); setFilename(file.name); try { const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}); const sheet=workbook.Sheets[workbook.SheetNames[0]]; const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""}); const next=raw.map((row,index)=>({row:index+2,material:String(row.Material??row.material??"").trim(),quantity:Number(row.Quantity??row.quantity),supplier:String(row.Supplier??row.supplier??"").trim(),totalCostUgx:Number(row["Total Cost"]??row.totalCost??row["Total Cost (UGX)"]),receivedDate:dateValue(row["Date Received"]??row.receivedDate),notes:String(row.Notes??row.notes??"").trim()})); const names=new Set(materials.map((m)=>m.name.toLowerCase())); const supplierNames=new Set(suppliers.map((s)=>s.name.toLowerCase())); const seen=new Set<string>(); const checked=next.map((item)=>{const problems:string[]=[]; const key=`${item.material.toLowerCase()}|${item.supplier.toLowerCase()}|${item.quantity}|${item.totalCostUgx}|${item.receivedDate}`; if(!item.material) problems.push("Missing material"); else if(!names.has(item.material.toLowerCase())) problems.push("Unknown material"); if(!Number.isFinite(item.quantity)||item.quantity<=0) problems.push("Quantity must be positive"); if(!item.supplier) problems.push("Missing supplier"); else if(!supplierNames.has(item.supplier.toLowerCase())) problems.push("Unknown supplier"); if(!Number.isInteger(item.totalCostUgx)||item.totalCostUgx<=0) problems.push("Total cost must be a positive whole UGX amount"); if(!/^\d{4}-\d{2}-\d{2}$/.test(item.receivedDate)) problems.push("Invalid date"); if(seen.has(key)) problems.push("Duplicate row"); seen.add(key); return {...item,problems};}); setRows(checked); const canonical = checked.filter((item)=>item.problems.length===0).map(({row,problems,...item})=>item); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(canonical))); setImportHash(Array.from(new Uint8Array(digest)).map((byte)=>byte.toString(16).padStart(2,"0")).join("")); } catch { setError("Unable to parse this workbook. Use the supplied template columns."); setRows([]); } }
  function downloadTemplate() { const sheet=XLSX.utils.json_to_sheet([{Material:"Charcoal",Quantity:6,Supplier:"", "Total Cost":180000,"Date Received":"2026-08-29",Notes:""}]); const book=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book,sheet,"Raw Materials"); XLSX.writeFile(book,"raw-materials-template.xlsx"); }
  const valid=rows.filter((row)=>row.problems.length===0); return <section className="surface-card rounded-[32px] p-5"><p className="text-[11px] uppercase tracking-[0.18em] text-[#9CA3AF]">Excel import</p><h2 className="mt-2 text-xl font-semibold">Import Raw Materials</h2><p className="mt-2 text-sm leading-6 text-[#6B7280]">Upload, validate, preview, then confirm. Preview does not change stock or money.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={downloadTemplate} className="rounded-xl border border-[#D7DDE4] bg-white px-4 py-2.5 text-sm font-semibold">Download template</button><label className="cursor-pointer rounded-xl bg-[#5E2519] px-4 py-2.5 text-sm font-semibold text-white">Choose .xlsx<input type="file" accept=".xlsx" className="hidden" onChange={(event)=>void handleFile(event.target.files?.[0])}/></label></div>{error?<p className="mt-3 text-sm text-[#A52B20]">{error}</p>:null}{rows.length>0?<><p className="mt-4 text-sm font-semibold">Preview: {valid.length} valid / {rows.length} rows</p><div className="mt-3 max-h-60 overflow-auto rounded-xl border border-[#E4E7EB]"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="p-2">Row</th><th className="p-2">Material</th><th className="p-2">Quantity</th><th className="p-2">Cost</th><th className="p-2">Status</th></tr></thead><tbody>{rows.map((row)=><tr key={row.row} className="border-b"><td className="p-2">{row.row}</td><td className="p-2">{row.material}</td><td className="p-2">{row.quantity}</td><td className="p-2">{row.totalCostUgx}</td><td className={`p-2 ${row.problems.length?"text-[#A52B20]":"text-[#287241]"}`}>{row.problems.length?row.problems.join(", "):"Valid"}</td></tr>)}</tbody></table></div>{valid.length===rows.length?<form action={action} className="mt-4"><input type="hidden" name="filename" value={filename}/><input type="hidden" name="rows" value={JSON.stringify(valid)}/><input type="hidden" name="import_hash" value={importHash}/><input type="hidden" name="batch_number" value={`RM-IMP-${importHash.slice(0,16)}`}/><button className="rounded-xl bg-[#287241] px-4 py-2.5 text-sm font-semibold text-white">Confirm import</button></form>:<p className="mt-3 text-sm text-[#A52B20]">Fix invalid rows and upload again before confirming.</p>}</>:null}</section>;
}
